// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk3VygYBELbSptHa0IZ-3SOVR5tsR4v-I',
    appId: '1:276499509152:web:ed8a8e614e5f9219e43ec5',
    messagingSenderId: '276499509152',
    projectId: 'nusa-f38ea',
    authDomain: 'nusa-f38ea.firebaseapp.com',
    storageBucket: 'nusa-f38ea.firebasestorage.app',
    measurementId: 'G-2XWQ2GTPLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKmQ2zz6w-Ox0127d9cNeg86J37_ofCBI',
    appId: '1:276499509152:android:907eff28f81f34c0e43ec5',
    messagingSenderId: '276499509152',
    projectId: 'nusa-f38ea',
    storageBucket: 'nusa-f38ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf1KAJSaPf9XtdsxGIbWdxZDXzRFkXOms',
    appId: '1:276499509152:ios:45a56768fbd55431e43ec5',
    messagingSenderId: '276499509152',
    projectId: 'nusa-f38ea',
    storageBucket: 'nusa-f38ea.firebasestorage.app',
    iosBundleId: 'com.example.nusa',
  );
}
